/**
 * \file keyboard.cpp
 * Implementation for keyboard.h
 */

#include"keyboard.h"

static const KeyboardLayout US =
{
	"US",
	{
		{0x00, "Reserved", KeyCategory::HIDDEN},
		{0x01, "ErrorRollOver", KeyCategory::HIDDEN},
		{0x02, "POSTFail", KeyCategory::HIDDEN},
		{0x03, "ErrorUndefined", KeyCategory::HIDDEN},
		{0x04, "A", KeyCategory::LETTER},
		{0x05, "B", KeyCategory::LETTER},
		{0x06, "C", KeyCategory::LETTER},
		{0x07, "D", KeyCategory::LETTER},
		{0x08, "E", KeyCategory::LETTER},
		{0x09, "F", KeyCategory::LETTER},
		{0x0a, "G", KeyCategory::LETTER},
		{0x0b, "H", KeyCategory::LETTER},
		{0x0c, "I", KeyCategory::LETTER},
		{0x0d, "J", KeyCategory::LETTER},
		{0x0e, "K", KeyCategory::LETTER},
		{0x0f, "L", KeyCategory::LETTER},
		{0x10, "M", KeyCategory::LETTER},
		{0x11, "N", KeyCategory::LETTER},
		{0x12, "O", KeyCategory::LETTER},
		{0x13, "P", KeyCategory::LETTER},
		{0x14, "Q", KeyCategory::LETTER},
		{0x15, "R", KeyCategory::LETTER},
		{0x16, "S", KeyCategory::LETTER},
		{0x17, "T", KeyCategory::LETTER},
		{0x18, "U", KeyCategory::LETTER},
		{0x19, "V", KeyCategory::LETTER},
		{0x1a, "W", KeyCategory::LETTER},
		{0x1b, "X", KeyCategory::LETTER},
		{0x1c, "Y", KeyCategory::LETTER},
		{0x1d, "Z", KeyCategory::LETTER},
		{0x1e, "1 !", KeyCategory::NUMBER},
		{0x1f, "2 @", KeyCategory::NUMBER},
		{0x20, "3 #", KeyCategory::NUMBER},
		{0x21, "4 $", KeyCategory::NUMBER},
		{0x22, "5 %", KeyCategory::NUMBER},
		{0x23, "6 ^", KeyCategory::NUMBER},
		{0x24, "7 &", KeyCategory::NUMBER},
		{0x25, "8 *", KeyCategory::NUMBER},
		{0x26, "9 (", KeyCategory::NUMBER},
		{0x27, "0 )", KeyCategory::NUMBER},
		{0x28, "Enter", KeyCategory::OTHER},
		{0x29, "ESC", KeyCategory::OTHER},
		{0x2a, "Backspace", KeyCategory::OTHER},
		{0x2b, "Tab", KeyCategory::OTHER},
		{0x2c, "Space", KeyCategory::OTHER},
		{0x2d, "- _", KeyCategory::OTHER},
		{0x2e, "= +", KeyCategory::OTHER},
		{0x2f, "[ {", KeyCategory::OTHER},
		{0x30, "] }", KeyCategory::OTHER},
		{0x31, "\\ |", KeyCategory::OTHER},
		{0x32, "[Non-US]", KeyCategory::HIDDEN},
		{0x33, "; :", KeyCategory::OTHER},
		{0x34, "' \"", KeyCategory::OTHER},
		{0x35, "` ~", KeyCategory::OTHER},
		{0x36, ", <", KeyCategory::OTHER},
		{0x37, ". >", KeyCategory::OTHER},
		{0x38, "/ ?", KeyCategory::OTHER},
		{0x39, "Caps Lock", KeyCategory::OTHER},
		{0x3a, "F1", KeyCategory::FUNCTION},
		{0x3b, "F2", KeyCategory::FUNCTION},
		{0x3c, "F3", KeyCategory::FUNCTION},
		{0x3d, "F4", KeyCategory::FUNCTION},
		{0x3e, "F5", KeyCategory::FUNCTION},
		{0x3f, "F6", KeyCategory::FUNCTION},
		{0x40, "F7", KeyCategory::FUNCTION},
		{0x41, "F8", KeyCategory::FUNCTION},
		{0x42, "F9", KeyCategory::FUNCTION},
		{0x43, "F10", KeyCategory::FUNCTION},
		{0x44, "F11", KeyCategory::FUNCTION},
		{0x45, "F12", KeyCategory::FUNCTION},
		{0x46, "Print Screen", KeyCategory::OTHER},
		{0x47, "Scroll Lock", KeyCategory::OTHER},
		{0x48, "Pause", KeyCategory::OTHER},
		{0x49, "Insert", KeyCategory::NAV},
		{0x4a, "Home", KeyCategory::NAV},
		{0x4b, "Page Up", KeyCategory::NAV},
		{0x4c, "Delete", KeyCategory::NAV},
		{0x4d, "End", KeyCategory::NAV},
		{0x4e, "Page Down", KeyCategory::NAV},
		{0x4f, "Right Arrow", KeyCategory::NAV},
		{0x50, "Left Arrow", KeyCategory::NAV},
		{0x51, "Down Arrow", KeyCategory::NAV},
		{0x52, "Up Arrow", KeyCategory::NAV},
		{0x53, "Num Lock", KeyCategory::NUMPAD},
		{0x54, "Numpad /", KeyCategory::NUMPAD},
		{0x55, "Numpad *", KeyCategory::NUMPAD},
		{0x56, "Numpad -", KeyCategory::NUMPAD},
		{0x57, "Numpad +", KeyCategory::NUMPAD},
		{0x58, "Numpad Enter", KeyCategory::NUMPAD},
		{0x59, "Numpad 1", KeyCategory::NUMPAD},
		{0x5a, "Numpad 2", KeyCategory::NUMPAD},
		{0x5b, "Numpad 3", KeyCategory::NUMPAD},
		{0x5c, "Numpad 4", KeyCategory::NUMPAD},
		{0x5d, "Numpad 5", KeyCategory::NUMPAD},
		{0x5e, "Numpad 6", KeyCategory::NUMPAD},
		{0x5f, "Numpad 7", KeyCategory::NUMPAD},
		{0x60, "Numpad 8", KeyCategory::NUMPAD},
		{0x61, "Numpad 9", KeyCategory::NUMPAD},
		{0x62, "Numpad 0", KeyCategory::NUMPAD},
		{0x63, "Numpad Decimal", KeyCategory::NUMPAD},
		{0x64, "[Non-US]", KeyCategory::HIDDEN},
		{0x65, "Application", KeyCategory::HIDDEN},
		{0x66, "Power", KeyCategory::HIDDEN},
		{0x67, "Numpad =", KeyCategory::HIDDEN},
		{0x68, "F13", KeyCategory::FUNCTION},
		{0x69, "F14", KeyCategory::FUNCTION},
		{0x6a, "F15", KeyCategory::FUNCTION},
		{0x6b, "F16", KeyCategory::FUNCTION},
		{0x6c, "F17", KeyCategory::FUNCTION},
		{0x6d, "F18", KeyCategory::FUNCTION},
		{0x6e, "F19", KeyCategory::FUNCTION},
		{0x6f, "F20", KeyCategory::FUNCTION},
		{0x70, "F21", KeyCategory::FUNCTION},
		{0x71, "F22", KeyCategory::FUNCTION},
		{0x72, "F23", KeyCategory::FUNCTION},
		{0x73, "F24", KeyCategory::FUNCTION},
		{0x74, "Execute", KeyCategory::HIDDEN},
		{0x75, "Help", KeyCategory::HIDDEN},
		{0x76, "Menu", KeyCategory::OTHER},
		{0x77, "Select", KeyCategory::HIDDEN},
		{0x78, "Stop", KeyCategory::HIDDEN},
		{0x79, "Again", KeyCategory::HIDDEN},
		{0x7a, "Undo", KeyCategory::HIDDEN},
		{0x7b, "Cut", KeyCategory::HIDDEN},
		{0x7c, "Copy", KeyCategory::HIDDEN},
		{0x7d, "Paste", KeyCategory::HIDDEN},
		{0x7e, "Find", KeyCategory::HIDDEN},
		{0x7f, "Mute", KeyCategory::OTHER},
		{0x80, "Volume Up", KeyCategory::OTHER},
		{0x81, "Volume Down", KeyCategory::OTHER},
		{0x82, "Locking Caps Lock", KeyCategory::HIDDEN},
		{0x83, "Locking Num Lock", KeyCategory::HIDDEN},
		{0x84, "Locking Scroll Lock", KeyCategory::HIDDEN},
		{0x85, "Numpad Comma", KeyCategory::HIDDEN},
		{0x86, "Numpad Equal Sign", KeyCategory::HIDDEN},
		{0x87, "", KeyCategory::HIDDEN},
		{0x88, "", KeyCategory::HIDDEN},
		{0x89, "", KeyCategory::HIDDEN},
		{0x8a, "", KeyCategory::HIDDEN},
		{0x8b, "", KeyCategory::HIDDEN},
		{0x8c, "", KeyCategory::HIDDEN},
		{0x8d, "", KeyCategory::HIDDEN},
		{0x8e, "", KeyCategory::HIDDEN},
		{0x8f, "", KeyCategory::HIDDEN},
		{0x90, "", KeyCategory::HIDDEN},
		{0x91, "", KeyCategory::HIDDEN},
		{0x92, "", KeyCategory::HIDDEN},
		{0x93, "", KeyCategory::HIDDEN},
		{0x94, "", KeyCategory::HIDDEN},
		{0x95, "", KeyCategory::HIDDEN},
		{0x96, "", KeyCategory::HIDDEN},
		{0x97, "", KeyCategory::HIDDEN},
		{0x98, "", KeyCategory::HIDDEN},
		{0x99, "", KeyCategory::HIDDEN},
		{0x9a, "", KeyCategory::HIDDEN},
		{0x9b, "", KeyCategory::HIDDEN},
		{0x9c, "", KeyCategory::HIDDEN},
		{0x9d, "", KeyCategory::HIDDEN},
		{0x9e, "", KeyCategory::HIDDEN},
		{0x9f, "", KeyCategory::HIDDEN},
		{0xa0, "", KeyCategory::HIDDEN},
		{0xa1, "", KeyCategory::HIDDEN},
		{0xa2, "", KeyCategory::HIDDEN},
		{0xa3, "", KeyCategory::HIDDEN},
		{0xa4, "", KeyCategory::HIDDEN},
		{0xa5, "Reserved", KeyCategory::HIDDEN},
		{0xa6, "Reserved", KeyCategory::HIDDEN},
		{0xa7, "Reserved", KeyCategory::HIDDEN},
		{0xa8, "Reserved", KeyCategory::HIDDEN},
		{0xa9, "Reserved", KeyCategory::HIDDEN},
		{0xaa, "Reserved", KeyCategory::HIDDEN},
		{0xab, "Reserved", KeyCategory::HIDDEN},
		{0xac, "Reserved", KeyCategory::HIDDEN},
		{0xad, "Reserved", KeyCategory::HIDDEN},
		{0xae, "Reserved", KeyCategory::HIDDEN},
		{0xaf, "Reserved", KeyCategory::HIDDEN},
		{0xb0, "", KeyCategory::HIDDEN},
		{0xb1, "", KeyCategory::HIDDEN},
		{0xb2, "", KeyCategory::HIDDEN},
		{0xb3, "", KeyCategory::HIDDEN},
		{0xb4, "", KeyCategory::HIDDEN},
		{0xb5, "", KeyCategory::HIDDEN},
		{0xb6, "", KeyCategory::HIDDEN},
		{0xb7, "", KeyCategory::HIDDEN},
		{0xb8, "", KeyCategory::HIDDEN},
		{0xb9, "", KeyCategory::HIDDEN},
		{0xba, "", KeyCategory::HIDDEN},
		{0xbb, "", KeyCategory::HIDDEN},
		{0xbc, "", KeyCategory::HIDDEN},
		{0xbd, "", KeyCategory::HIDDEN},
		{0xbe, "", KeyCategory::HIDDEN},
		{0xbf, "", KeyCategory::HIDDEN},
		{0xc0, "", KeyCategory::HIDDEN},
		{0xc1, "", KeyCategory::HIDDEN},
		{0xc2, "", KeyCategory::HIDDEN},
		{0xc3, "", KeyCategory::HIDDEN},
		{0xc4, "", KeyCategory::HIDDEN},
		{0xc5, "", KeyCategory::HIDDEN},
		{0xc6, "", KeyCategory::HIDDEN},
		{0xc7, "", KeyCategory::HIDDEN},
		{0xc8, "", KeyCategory::HIDDEN},
		{0xc9, "", KeyCategory::HIDDEN},
		{0xca, "", KeyCategory::HIDDEN},
		{0xcb, "", KeyCategory::HIDDEN},
		{0xcc, "", KeyCategory::HIDDEN},
		{0xcd, "", KeyCategory::HIDDEN},
		{0xce, "", KeyCategory::HIDDEN},
		{0xcf, "", KeyCategory::HIDDEN},
		{0xd0, "", KeyCategory::HIDDEN},
		{0xd1, "", KeyCategory::HIDDEN},
		{0xd2, "", KeyCategory::HIDDEN},
		{0xd3, "", KeyCategory::HIDDEN},
		{0xd4, "", KeyCategory::HIDDEN},
		{0xd5, "", KeyCategory::HIDDEN},
		{0xd6, "", KeyCategory::HIDDEN},
		{0xd7, "", KeyCategory::HIDDEN},
		{0xd8, "", KeyCategory::HIDDEN},
		{0xd9, "", KeyCategory::HIDDEN},
		{0xda, "", KeyCategory::HIDDEN},
		{0xdb, "", KeyCategory::HIDDEN},
		{0xdc, "", KeyCategory::HIDDEN},
		{0xdd, "", KeyCategory::HIDDEN},
		{0xde, "Reserved", KeyCategory::HIDDEN},
		{0xdf, "Reserved", KeyCategory::HIDDEN},
		{0xe0, "Left Control", KeyCategory::HIDDEN},
		{0xe1, "Left Shift", KeyCategory::HIDDEN},
		{0xe2, "Left Alt", KeyCategory::HIDDEN},
		{0xe3, "Left GUI", KeyCategory::HIDDEN},
		{0xe4, "Right Control", KeyCategory::HIDDEN},
		{0xe5, "Right Shift", KeyCategory::HIDDEN},
		{0xe6, "Right Alt", KeyCategory::HIDDEN},
		{0xe7, "Right GUI", KeyCategory::HIDDEN},
		{0xe8, "Reserved", KeyCategory::HIDDEN},
		{0xe9, "Reserved", KeyCategory::HIDDEN},
		{0xea, "Reserved", KeyCategory::HIDDEN},
		{0xeb, "Reserved", KeyCategory::HIDDEN},
		{0xec, "Reserved", KeyCategory::HIDDEN},
		{0xed, "Reserved", KeyCategory::HIDDEN},
		{0xee, "Reserved", KeyCategory::HIDDEN},
		{0xef, "Reserved", KeyCategory::HIDDEN},
		{0xf0, "Reserved", KeyCategory::HIDDEN},
		{0xf1, "Reserved", KeyCategory::HIDDEN},
		{0xf2, "Reserved", KeyCategory::HIDDEN},
		{0xf3, "Reserved", KeyCategory::HIDDEN},
		{0xf4, "Reserved", KeyCategory::HIDDEN},
		{0xf5, "Reserved", KeyCategory::HIDDEN},
		{0xf6, "Reserved", KeyCategory::HIDDEN},
		{0xf7, "Reserved", KeyCategory::HIDDEN},
		{0xf8, "Reserved", KeyCategory::HIDDEN},
		{0xf9, "Reserved", KeyCategory::HIDDEN},
		{0xfa, "Reserved", KeyCategory::HIDDEN},
		{0xfb, "Reserved", KeyCategory::HIDDEN},
		{0xfc, "Reserved", KeyCategory::HIDDEN},
		{0xfd, "Reserved", KeyCategory::HIDDEN},
		{0xfe, "Reserved", KeyCategory::HIDDEN},
		{0xff, "Reserved", KeyCategory::HIDDEN}
	}
};

static const KeyboardLayout FRENCH =
{
	"French (Legacy)",
	{
		{0x00, "Reserved", KeyCategory::HIDDEN},
		{0x01, "ErrorRollOver", KeyCategory::HIDDEN},
		{0x02, "POSTFail", KeyCategory::HIDDEN},
		{0x03, "ErrorUndefined", KeyCategory::HIDDEN},
		{0x04, "Q", KeyCategory::LETTER},
		{0x05, "B", KeyCategory::LETTER},
		{0x06, "C", KeyCategory::LETTER},
		{0x07, "D", KeyCategory::LETTER},
		{0x08, "E €", KeyCategory::LETTER},
		{0x09, "F", KeyCategory::LETTER},
		{0x0a, "G", KeyCategory::LETTER},
		{0x0b, "H", KeyCategory::LETTER},
		{0x0c, "I", KeyCategory::LETTER},
		{0x0d, "J", KeyCategory::LETTER},
		{0x0e, "K", KeyCategory::LETTER},
		{0x0f, "L", KeyCategory::LETTER},
		{0x10, ", ?", KeyCategory::OTHER},
		{0x11, "N", KeyCategory::LETTER},
		{0x12, "O", KeyCategory::LETTER},
		{0x13, "P", KeyCategory::LETTER},
		{0x14, "A", KeyCategory::LETTER},
		{0x15, "R", KeyCategory::LETTER},
		{0x16, "S", KeyCategory::LETTER},
		{0x17, "T", KeyCategory::LETTER},
		{0x18, "U", KeyCategory::LETTER},
		{0x19, "V", KeyCategory::LETTER},
		{0x1a, "Z", KeyCategory::LETTER},
		{0x1b, "X", KeyCategory::LETTER},
		{0x1c, "Y", KeyCategory::LETTER},
		{0x1d, "W", KeyCategory::LETTER},
		{0x1e, "1 &", KeyCategory::NUMBER},
		{0x1f, "2 é ~", KeyCategory::NUMBER},
		{0x20, "3 \" #", KeyCategory::NUMBER},
		{0x21, "4 ' {", KeyCategory::NUMBER},
		{0x22, "5 ( [", KeyCategory::NUMBER},
		{0x23, "6 - |", KeyCategory::NUMBER},
		{0x24, "7 è `", KeyCategory::NUMBER},
		{0x25, "8 - \\", KeyCategory::NUMBER},
		{0x26, "9 ç", KeyCategory::NUMBER},
		{0x27, "0 à @", KeyCategory::NUMBER},
		{0x28, "Enter", KeyCategory::OTHER},
		{0x29, "ESC", KeyCategory::OTHER},
		{0x2a, "Backspace", KeyCategory::OTHER},
		{0x2b, "Tab", KeyCategory::OTHER},
		{0x2c, "Space", KeyCategory::OTHER},
		{0x2d, "° ) ]", KeyCategory::OTHER},
		{0x2e, "+ = }", KeyCategory::OTHER},
		{0x2f, "^ ̈", KeyCategory::OTHER},
		{0x30, "£ $ ¤", KeyCategory::OTHER},
		{0x31, "[Non-French]", KeyCategory::HIDDEN},
		{0x32, "* µ", KeyCategory::HIDDEN},
		{0x33, "M", KeyCategory::LETTER},
		{0x34, "ù %", KeyCategory::OTHER},
		{0x35, "²", KeyCategory::OTHER},
		{0x36, "; .", KeyCategory::OTHER},
		{0x37, ": /", KeyCategory::OTHER},
		{0x38, "! §", KeyCategory::OTHER},
		{0x39, "Caps Lock", KeyCategory::OTHER},
		{0x3a, "F1", KeyCategory::FUNCTION},
		{0x3b, "F2", KeyCategory::FUNCTION},
		{0x3c, "F3", KeyCategory::FUNCTION},
		{0x3d, "F4", KeyCategory::FUNCTION},
		{0x3e, "F5", KeyCategory::FUNCTION},
		{0x3f, "F6", KeyCategory::FUNCTION},
		{0x40, "F7", KeyCategory::FUNCTION},
		{0x41, "F8", KeyCategory::FUNCTION},
		{0x42, "F9", KeyCategory::FUNCTION},
		{0x43, "F10", KeyCategory::FUNCTION},
		{0x44, "F11", KeyCategory::FUNCTION},
		{0x45, "F12", KeyCategory::FUNCTION},
		{0x46, "Print Screen", KeyCategory::OTHER},
		{0x47, "Scroll Lock", KeyCategory::OTHER},
		{0x48, "Pause", KeyCategory::OTHER},
		{0x49, "Insert", KeyCategory::NAV},
		{0x4a, "Home", KeyCategory::NAV},
		{0x4b, "Page Up", KeyCategory::NAV},
		{0x4c, "Delete", KeyCategory::NAV},
		{0x4d, "End", KeyCategory::NAV},
		{0x4e, "Page Down", KeyCategory::NAV},
		{0x4f, "Right Arrow", KeyCategory::NAV},
		{0x50, "Left Arrow", KeyCategory::NAV},
		{0x51, "Down Arrow", KeyCategory::NAV},
		{0x52, "Up Arrow", KeyCategory::NAV},
		{0x53, "Num Lock", KeyCategory::NUMPAD},
		{0x54, "Numpad /", KeyCategory::NUMPAD},
		{0x55, "Numpad *", KeyCategory::NUMPAD},
		{0x56, "Numpad -", KeyCategory::NUMPAD},
		{0x57, "Numpad +", KeyCategory::NUMPAD},
		{0x58, "Numpad Enter", KeyCategory::NUMPAD},
		{0x59, "Numpad 1", KeyCategory::NUMPAD},
		{0x5a, "Numpad 2", KeyCategory::NUMPAD},
		{0x5b, "Numpad 3", KeyCategory::NUMPAD},
		{0x5c, "Numpad 4", KeyCategory::NUMPAD},
		{0x5d, "Numpad 5", KeyCategory::NUMPAD},
		{0x5e, "Numpad 6", KeyCategory::NUMPAD},
		{0x5f, "Numpad 7", KeyCategory::NUMPAD},
		{0x60, "Numpad 8", KeyCategory::NUMPAD},
		{0x61, "Numpad 9", KeyCategory::NUMPAD},
		{0x62, "Numpad 0", KeyCategory::NUMPAD},
		{0x63, "Numpad Decimal", KeyCategory::NUMPAD},
		{0x64, "< >", KeyCategory::OTHER},
		{0x65, "Application", KeyCategory::HIDDEN},
		{0x66, "Power", KeyCategory::HIDDEN},
		{0x67, "Numpad =", KeyCategory::HIDDEN},
		{0x68, "F13", KeyCategory::FUNCTION},
		{0x69, "F14", KeyCategory::FUNCTION},
		{0x6a, "F15", KeyCategory::FUNCTION},
		{0x6b, "F16", KeyCategory::FUNCTION},
		{0x6c, "F17", KeyCategory::FUNCTION},
		{0x6d, "F18", KeyCategory::FUNCTION},
		{0x6e, "F19", KeyCategory::FUNCTION},
		{0x6f, "F20", KeyCategory::FUNCTION},
		{0x70, "F21", KeyCategory::FUNCTION},
		{0x71, "F22", KeyCategory::FUNCTION},
		{0x72, "F23", KeyCategory::FUNCTION},
		{0x73, "F24", KeyCategory::FUNCTION},
		{0x74, "Execute", KeyCategory::HIDDEN},
		{0x75, "Help", KeyCategory::HIDDEN},
		{0x76, "Menu", KeyCategory::OTHER},
		{0x77, "Select", KeyCategory::HIDDEN},
		{0x78, "Stop", KeyCategory::HIDDEN},
		{0x79, "Again", KeyCategory::HIDDEN},
		{0x7a, "Undo", KeyCategory::HIDDEN},
		{0x7b, "Cut", KeyCategory::HIDDEN},
		{0x7c, "Copy", KeyCategory::HIDDEN},
		{0x7d, "Paste", KeyCategory::HIDDEN},
		{0x7e, "Find", KeyCategory::HIDDEN},
		{0x7f, "Mute", KeyCategory::OTHER},
		{0x80, "Volume Up", KeyCategory::OTHER},
		{0x81, "Volume Down", KeyCategory::OTHER},
		{0x82, "Locking Caps Lock", KeyCategory::HIDDEN},
		{0x83, "Locking Num Lock", KeyCategory::HIDDEN},
		{0x84, "Locking Scroll Lock", KeyCategory::HIDDEN},
		{0x85, "Numpad Comma", KeyCategory::HIDDEN},
		{0x86, "Numpad Equal Sign", KeyCategory::HIDDEN},
		{0x87, "", KeyCategory::HIDDEN},
		{0x88, "", KeyCategory::HIDDEN},
		{0x89, "", KeyCategory::HIDDEN},
		{0x8a, "", KeyCategory::HIDDEN},
		{0x8b, "", KeyCategory::HIDDEN},
		{0x8c, "", KeyCategory::HIDDEN},
		{0x8d, "", KeyCategory::HIDDEN},
		{0x8e, "", KeyCategory::HIDDEN},
		{0x8f, "", KeyCategory::HIDDEN},
		{0x90, "", KeyCategory::HIDDEN},
		{0x91, "", KeyCategory::HIDDEN},
		{0x92, "", KeyCategory::HIDDEN},
		{0x93, "", KeyCategory::HIDDEN},
		{0x94, "", KeyCategory::HIDDEN},
		{0x95, "", KeyCategory::HIDDEN},
		{0x96, "", KeyCategory::HIDDEN},
		{0x97, "", KeyCategory::HIDDEN},
		{0x98, "", KeyCategory::HIDDEN},
		{0x99, "", KeyCategory::HIDDEN},
		{0x9a, "", KeyCategory::HIDDEN},
		{0x9b, "", KeyCategory::HIDDEN},
		{0x9c, "", KeyCategory::HIDDEN},
		{0x9d, "", KeyCategory::HIDDEN},
		{0x9e, "", KeyCategory::HIDDEN},
		{0x9f, "", KeyCategory::HIDDEN},
		{0xa0, "", KeyCategory::HIDDEN},
		{0xa1, "", KeyCategory::HIDDEN},
		{0xa2, "", KeyCategory::HIDDEN},
		{0xa3, "", KeyCategory::HIDDEN},
		{0xa4, "", KeyCategory::HIDDEN},
		{0xa5, "Reserved", KeyCategory::HIDDEN},
		{0xa6, "Reserved", KeyCategory::HIDDEN},
		{0xa7, "Reserved", KeyCategory::HIDDEN},
		{0xa8, "Reserved", KeyCategory::HIDDEN},
		{0xa9, "Reserved", KeyCategory::HIDDEN},
		{0xaa, "Reserved", KeyCategory::HIDDEN},
		{0xab, "Reserved", KeyCategory::HIDDEN},
		{0xac, "Reserved", KeyCategory::HIDDEN},
		{0xad, "Reserved", KeyCategory::HIDDEN},
		{0xae, "Reserved", KeyCategory::HIDDEN},
		{0xaf, "Reserved", KeyCategory::HIDDEN},
		{0xb0, "", KeyCategory::HIDDEN},
		{0xb1, "", KeyCategory::HIDDEN},
		{0xb2, "", KeyCategory::HIDDEN},
		{0xb3, "", KeyCategory::HIDDEN},
		{0xb4, "", KeyCategory::HIDDEN},
		{0xb5, "", KeyCategory::HIDDEN},
		{0xb6, "", KeyCategory::HIDDEN},
		{0xb7, "", KeyCategory::HIDDEN},
		{0xb8, "", KeyCategory::HIDDEN},
		{0xb9, "", KeyCategory::HIDDEN},
		{0xba, "", KeyCategory::HIDDEN},
		{0xbb, "", KeyCategory::HIDDEN},
		{0xbc, "", KeyCategory::HIDDEN},
		{0xbd, "", KeyCategory::HIDDEN},
		{0xbe, "", KeyCategory::HIDDEN},
		{0xbf, "", KeyCategory::HIDDEN},
		{0xc0, "", KeyCategory::HIDDEN},
		{0xc1, "", KeyCategory::HIDDEN},
		{0xc2, "", KeyCategory::HIDDEN},
		{0xc3, "", KeyCategory::HIDDEN},
		{0xc4, "", KeyCategory::HIDDEN},
		{0xc5, "", KeyCategory::HIDDEN},
		{0xc6, "", KeyCategory::HIDDEN},
		{0xc7, "", KeyCategory::HIDDEN},
		{0xc8, "", KeyCategory::HIDDEN},
		{0xc9, "", KeyCategory::HIDDEN},
		{0xca, "", KeyCategory::HIDDEN},
		{0xcb, "", KeyCategory::HIDDEN},
		{0xcc, "", KeyCategory::HIDDEN},
		{0xcd, "", KeyCategory::HIDDEN},
		{0xce, "", KeyCategory::HIDDEN},
		{0xcf, "", KeyCategory::HIDDEN},
		{0xd0, "", KeyCategory::HIDDEN},
		{0xd1, "", KeyCategory::HIDDEN},
		{0xd2, "", KeyCategory::HIDDEN},
		{0xd3, "", KeyCategory::HIDDEN},
		{0xd4, "", KeyCategory::HIDDEN},
		{0xd5, "", KeyCategory::HIDDEN},
		{0xd6, "", KeyCategory::HIDDEN},
		{0xd7, "", KeyCategory::HIDDEN},
		{0xd8, "", KeyCategory::HIDDEN},
		{0xd9, "", KeyCategory::HIDDEN},
		{0xda, "", KeyCategory::HIDDEN},
		{0xdb, "", KeyCategory::HIDDEN},
		{0xdc, "", KeyCategory::HIDDEN},
		{0xdd, "", KeyCategory::HIDDEN},
		{0xde, "Reserved", KeyCategory::HIDDEN},
		{0xdf, "Reserved", KeyCategory::HIDDEN},
		{0xe0, "Left Control", KeyCategory::HIDDEN},
		{0xe1, "Left Shift", KeyCategory::HIDDEN},
		{0xe2, "Left Alt", KeyCategory::HIDDEN},
		{0xe3, "Left GUI", KeyCategory::HIDDEN},
		{0xe4, "Right Control", KeyCategory::HIDDEN},
		{0xe5, "Right Shift", KeyCategory::HIDDEN},
		{0xe6, "Right Alt", KeyCategory::HIDDEN},
		{0xe7, "Right GUI", KeyCategory::HIDDEN},
		{0xe8, "Reserved", KeyCategory::HIDDEN},
		{0xe9, "Reserved", KeyCategory::HIDDEN},
		{0xea, "Reserved", KeyCategory::HIDDEN},
		{0xeb, "Reserved", KeyCategory::HIDDEN},
		{0xec, "Reserved", KeyCategory::HIDDEN},
		{0xed, "Reserved", KeyCategory::HIDDEN},
		{0xee, "Reserved", KeyCategory::HIDDEN},
		{0xef, "Reserved", KeyCategory::HIDDEN},
		{0xf0, "Reserved", KeyCategory::HIDDEN},
		{0xf1, "Reserved", KeyCategory::HIDDEN},
		{0xf2, "Reserved", KeyCategory::HIDDEN},
		{0xf3, "Reserved", KeyCategory::HIDDEN},
		{0xf4, "Reserved", KeyCategory::HIDDEN},
		{0xf5, "Reserved", KeyCategory::HIDDEN},
		{0xf6, "Reserved", KeyCategory::HIDDEN},
		{0xf7, "Reserved", KeyCategory::HIDDEN},
		{0xf8, "Reserved", KeyCategory::HIDDEN},
		{0xf9, "Reserved", KeyCategory::HIDDEN},
		{0xfa, "Reserved", KeyCategory::HIDDEN},
		{0xfb, "Reserved", KeyCategory::HIDDEN},
		{0xfc, "Reserved", KeyCategory::HIDDEN},
		{0xfd, "Reserved", KeyCategory::HIDDEN},
		{0xfe, "Reserved", KeyCategory::HIDDEN},
		{0xff, "Reserved", KeyCategory::HIDDEN}
	}
};

static const KeyboardLayout GERMAN =
{
	"German",
	{
		{0x00, "Reserved", KeyCategory::HIDDEN},
		{0x01, "ErrorRollOver", KeyCategory::HIDDEN},
		{0x02, "POSTFail", KeyCategory::HIDDEN},
		{0x03, "ErrorUndefined", KeyCategory::HIDDEN},
		{0x04, "A", KeyCategory::LETTER},
		{0x05, "B", KeyCategory::LETTER},
		{0x06, "C", KeyCategory::LETTER},
		{0x07, "D", KeyCategory::LETTER},
		{0x08, "E €", KeyCategory::LETTER},
		{0x09, "F", KeyCategory::LETTER},
		{0x0a, "G", KeyCategory::LETTER},
		{0x0b, "H", KeyCategory::LETTER},
		{0x0c, "I", KeyCategory::LETTER},
		{0x0d, "J", KeyCategory::LETTER},
		{0x0e, "K", KeyCategory::LETTER},
		{0x0f, "L", KeyCategory::LETTER},
		{0x10, "M µ", KeyCategory::LETTER},
		{0x11, "N", KeyCategory::LETTER},
		{0x12, "O", KeyCategory::LETTER},
		{0x13, "P", KeyCategory::LETTER},
		{0x14, "Q @", KeyCategory::LETTER},
		{0x15, "R", KeyCategory::LETTER},
		{0x16, "S", KeyCategory::LETTER},
		{0x17, "T", KeyCategory::LETTER},
		{0x18, "U", KeyCategory::LETTER},
		{0x19, "V", KeyCategory::LETTER},
		{0x1a, "W", KeyCategory::LETTER},
		{0x1b, "X", KeyCategory::LETTER},
		{0x1c, "Z", KeyCategory::LETTER},
		{0x1d, "Y", KeyCategory::LETTER},
		{0x1e, "1 !", KeyCategory::NUMBER},
		{0x1f, "2 \" ²", KeyCategory::NUMBER},
		{0x20, "3 § ³", KeyCategory::NUMBER},
		{0x21, "4 $", KeyCategory::NUMBER},
		{0x22, "5 %", KeyCategory::NUMBER},
		{0x23, "6 &", KeyCategory::NUMBER},
		{0x24, "7 / {", KeyCategory::NUMBER},
		{0x25, "8 ( [", KeyCategory::NUMBER},
		{0x26, "9 ) ]", KeyCategory::NUMBER},
		{0x27, "0 = }", KeyCategory::NUMBER},
		{0x28, "Enter", KeyCategory::OTHER},
		{0x29, "ESC", KeyCategory::OTHER},
		{0x2a, "Backspace", KeyCategory::OTHER},
		{0x2b, "Tab", KeyCategory::OTHER},
		{0x2c, "Space", KeyCategory::OTHER},
		{0x2d, "ß ? \"", KeyCategory::OTHER},
		{0x2e, "´ `", KeyCategory::OTHER},
		{0x2f, "Ü", KeyCategory::LETTER},
		{0x30, "+ * ~", KeyCategory::OTHER},
		{0x31, "[Non-German]", KeyCategory::HIDDEN},
		{0x32, "# '", KeyCategory::OTHER},
		{0x33, "Ö", KeyCategory::LETTER},
		{0x34, "Ä", KeyCategory::LETTER},
		{0x35, "^ °", KeyCategory::OTHER},
		{0x36, ", ;", KeyCategory::OTHER},
		{0x37, ". :", KeyCategory::OTHER},
		{0x38, "- _", KeyCategory::OTHER},
		{0x39, "Caps Lock", KeyCategory::OTHER},
		{0x3a, "F1", KeyCategory::FUNCTION},
		{0x3b, "F2", KeyCategory::FUNCTION},
		{0x3c, "F3", KeyCategory::FUNCTION},
		{0x3d, "F4", KeyCategory::FUNCTION},
		{0x3e, "F5", KeyCategory::FUNCTION},
		{0x3f, "F6", KeyCategory::FUNCTION},
		{0x40, "F7", KeyCategory::FUNCTION},
		{0x41, "F8", KeyCategory::FUNCTION},
		{0x42, "F9", KeyCategory::FUNCTION},
		{0x43, "F10", KeyCategory::FUNCTION},
		{0x44, "F11", KeyCategory::FUNCTION},
		{0x45, "F12", KeyCategory::FUNCTION},
		{0x46, "Print Screen", KeyCategory::OTHER},
		{0x47, "Scroll Lock", KeyCategory::OTHER},
		{0x48, "Pause", KeyCategory::OTHER},
		{0x49, "Insert", KeyCategory::NAV},
		{0x4a, "Home", KeyCategory::NAV},
		{0x4b, "Page Up", KeyCategory::NAV},
		{0x4c, "Delete", KeyCategory::NAV},
		{0x4d, "End", KeyCategory::NAV},
		{0x4e, "Page Down", KeyCategory::NAV},
		{0x4f, "Right Arrow", KeyCategory::NAV},
		{0x50, "Left Arrow", KeyCategory::NAV},
		{0x51, "Down Arrow", KeyCategory::NAV},
		{0x52, "Up Arrow", KeyCategory::NAV},
		{0x53, "Num Lock", KeyCategory::NUMPAD},
		{0x54, "Numpad /", KeyCategory::NUMPAD},
		{0x55, "Numpad *", KeyCategory::NUMPAD},
		{0x56, "Numpad -", KeyCategory::NUMPAD},
		{0x57, "Numpad +", KeyCategory::NUMPAD},
		{0x58, "Numpad Enter", KeyCategory::NUMPAD},
		{0x59, "Numpad 1", KeyCategory::NUMPAD},
		{0x5a, "Numpad 2", KeyCategory::NUMPAD},
		{0x5b, "Numpad 3", KeyCategory::NUMPAD},
		{0x5c, "Numpad 4", KeyCategory::NUMPAD},
		{0x5d, "Numpad 5", KeyCategory::NUMPAD},
		{0x5e, "Numpad 6", KeyCategory::NUMPAD},
		{0x5f, "Numpad 7", KeyCategory::NUMPAD},
		{0x60, "Numpad 8", KeyCategory::NUMPAD},
		{0x61, "Numpad 9", KeyCategory::NUMPAD},
		{0x62, "Numpad 0", KeyCategory::NUMPAD},
		{0x63, "Numpad Decimal", KeyCategory::NUMPAD},
		{0x64, "< > |", KeyCategory::OTHER},
		{0x65, "Application", KeyCategory::HIDDEN},
		{0x66, "Power", KeyCategory::HIDDEN},
		{0x67, "Numpad =", KeyCategory::NUMPAD},
		{0x68, "F13", KeyCategory::FUNCTION},
		{0x69, "F14", KeyCategory::FUNCTION},
		{0x6a, "F15", KeyCategory::FUNCTION},
		{0x6b, "F16", KeyCategory::FUNCTION},
		{0x6c, "F17", KeyCategory::FUNCTION},
		{0x6d, "F18", KeyCategory::FUNCTION},
		{0x6e, "F19", KeyCategory::FUNCTION},
		{0x6f, "F20", KeyCategory::FUNCTION},
		{0x70, "F21", KeyCategory::FUNCTION},
		{0x71, "F22", KeyCategory::FUNCTION},
		{0x72, "F23", KeyCategory::FUNCTION},
		{0x73, "F24", KeyCategory::FUNCTION},
		{0x74, "Execute", KeyCategory::HIDDEN},
		{0x75, "Help", KeyCategory::HIDDEN},
		{0x76, "Menu", KeyCategory::OTHER},
		{0x77, "Select", KeyCategory::HIDDEN},
		{0x78, "Stop", KeyCategory::HIDDEN},
		{0x79, "Again", KeyCategory::HIDDEN},
		{0x7a, "Undo", KeyCategory::HIDDEN},
		{0x7b, "Cut", KeyCategory::HIDDEN},
		{0x7c, "Copy", KeyCategory::HIDDEN},
		{0x7d, "Paste", KeyCategory::HIDDEN},
		{0x7e, "Find", KeyCategory::HIDDEN},
		{0x7f, "Mute", KeyCategory::OTHER},
		{0x80, "Volume Up", KeyCategory::OTHER},
		{0x81, "Volume Down", KeyCategory::OTHER},
		{0x82, "Locking Caps Lock", KeyCategory::HIDDEN},
		{0x83, "Locking Num Lock", KeyCategory::HIDDEN},
		{0x84, "Locking Scroll Lock", KeyCategory::HIDDEN},
		{0x85, "Numpad Comma", KeyCategory::HIDDEN},
		{0x86, "Numpad Equal Sign", KeyCategory::HIDDEN},
		{0x87, "", KeyCategory::HIDDEN},
		{0x88, "", KeyCategory::HIDDEN},
		{0x89, "", KeyCategory::HIDDEN},
		{0x8a, "", KeyCategory::HIDDEN},
		{0x8b, "", KeyCategory::HIDDEN},
		{0x8c, "", KeyCategory::HIDDEN},
		{0x8d, "", KeyCategory::HIDDEN},
		{0x8e, "", KeyCategory::HIDDEN},
		{0x8f, "", KeyCategory::HIDDEN},
		{0x90, "", KeyCategory::HIDDEN},
		{0x91, "", KeyCategory::HIDDEN},
		{0x92, "", KeyCategory::HIDDEN},
		{0x93, "", KeyCategory::HIDDEN},
		{0x94, "", KeyCategory::HIDDEN},
		{0x95, "", KeyCategory::HIDDEN},
		{0x96, "", KeyCategory::HIDDEN},
		{0x97, "", KeyCategory::HIDDEN},
		{0x98, "", KeyCategory::HIDDEN},
		{0x99, "", KeyCategory::HIDDEN},
		{0x9a, "", KeyCategory::HIDDEN},
		{0x9b, "", KeyCategory::HIDDEN},
		{0x9c, "", KeyCategory::HIDDEN},
		{0x9d, "", KeyCategory::HIDDEN},
		{0x9e, "", KeyCategory::HIDDEN},
		{0x9f, "", KeyCategory::HIDDEN},
		{0xa0, "", KeyCategory::HIDDEN},
		{0xa1, "", KeyCategory::HIDDEN},
		{0xa2, "", KeyCategory::HIDDEN},
		{0xa3, "", KeyCategory::HIDDEN},
		{0xa4, "", KeyCategory::HIDDEN},
		{0xa5, "Reserved", KeyCategory::HIDDEN},
		{0xa6, "Reserved", KeyCategory::HIDDEN},
		{0xa7, "Reserved", KeyCategory::HIDDEN},
		{0xa8, "Reserved", KeyCategory::HIDDEN},
		{0xa9, "Reserved", KeyCategory::HIDDEN},
		{0xaa, "Reserved", KeyCategory::HIDDEN},
		{0xab, "Reserved", KeyCategory::HIDDEN},
		{0xac, "Reserved", KeyCategory::HIDDEN},
		{0xad, "Reserved", KeyCategory::HIDDEN},
		{0xae, "Reserved", KeyCategory::HIDDEN},
		{0xaf, "Reserved", KeyCategory::HIDDEN},
		{0xb0, "", KeyCategory::HIDDEN},
		{0xb1, "", KeyCategory::HIDDEN},
		{0xb2, "", KeyCategory::HIDDEN},
		{0xb3, "", KeyCategory::HIDDEN},
		{0xb4, "", KeyCategory::HIDDEN},
		{0xb5, "", KeyCategory::HIDDEN},
		{0xb6, "", KeyCategory::HIDDEN},
		{0xb7, "", KeyCategory::HIDDEN},
		{0xb8, "", KeyCategory::HIDDEN},
		{0xb9, "", KeyCategory::HIDDEN},
		{0xba, "", KeyCategory::HIDDEN},
		{0xbb, "", KeyCategory::HIDDEN},
		{0xbc, "", KeyCategory::HIDDEN},
		{0xbd, "", KeyCategory::HIDDEN},
		{0xbe, "", KeyCategory::HIDDEN},
		{0xbf, "", KeyCategory::HIDDEN},
		{0xc0, "", KeyCategory::HIDDEN},
		{0xc1, "", KeyCategory::HIDDEN},
		{0xc2, "", KeyCategory::HIDDEN},
		{0xc3, "", KeyCategory::HIDDEN},
		{0xc4, "", KeyCategory::HIDDEN},
		{0xc5, "", KeyCategory::HIDDEN},
		{0xc6, "", KeyCategory::HIDDEN},
		{0xc7, "", KeyCategory::HIDDEN},
		{0xc8, "", KeyCategory::HIDDEN},
		{0xc9, "", KeyCategory::HIDDEN},
		{0xca, "", KeyCategory::HIDDEN},
		{0xcb, "", KeyCategory::HIDDEN},
		{0xcc, "", KeyCategory::HIDDEN},
		{0xcd, "", KeyCategory::HIDDEN},
		{0xce, "", KeyCategory::HIDDEN},
		{0xcf, "", KeyCategory::HIDDEN},
		{0xd0, "", KeyCategory::HIDDEN},
		{0xd1, "", KeyCategory::HIDDEN},
		{0xd2, "", KeyCategory::HIDDEN},
		{0xd3, "", KeyCategory::HIDDEN},
		{0xd4, "", KeyCategory::HIDDEN},
		{0xd5, "", KeyCategory::HIDDEN},
		{0xd6, "", KeyCategory::HIDDEN},
		{0xd7, "", KeyCategory::HIDDEN},
		{0xd8, "", KeyCategory::HIDDEN},
		{0xd9, "", KeyCategory::HIDDEN},
		{0xda, "", KeyCategory::HIDDEN},
		{0xdb, "", KeyCategory::HIDDEN},
		{0xdc, "", KeyCategory::HIDDEN},
		{0xdd, "", KeyCategory::HIDDEN},
		{0xde, "Reserved", KeyCategory::HIDDEN},
		{0xdf, "Reserved", KeyCategory::HIDDEN},
		{0xe0, "Left Control", KeyCategory::HIDDEN},
		{0xe1, "Left Shift", KeyCategory::HIDDEN},
		{0xe2, "Left Alt", KeyCategory::HIDDEN},
		{0xe3, "Left GUI", KeyCategory::HIDDEN},
		{0xe4, "Right Control", KeyCategory::HIDDEN},
		{0xe5, "Right Shift", KeyCategory::HIDDEN},
		{0xe6, "Right Alt", KeyCategory::HIDDEN},
		{0xe7, "Right GUI", KeyCategory::HIDDEN},
		{0xe8, "Reserved", KeyCategory::HIDDEN},
		{0xe9, "Reserved", KeyCategory::HIDDEN},
		{0xea, "Reserved", KeyCategory::HIDDEN},
		{0xeb, "Reserved", KeyCategory::HIDDEN},
		{0xec, "Reserved", KeyCategory::HIDDEN},
		{0xed, "Reserved", KeyCategory::HIDDEN},
		{0xee, "Reserved", KeyCategory::HIDDEN},
		{0xef, "Reserved", KeyCategory::HIDDEN},
		{0xf0, "Reserved", KeyCategory::HIDDEN},
		{0xf1, "Reserved", KeyCategory::HIDDEN},
		{0xf2, "Reserved", KeyCategory::HIDDEN},
		{0xf3, "Reserved", KeyCategory::HIDDEN},
		{0xf4, "Reserved", KeyCategory::HIDDEN},
		{0xf5, "Reserved", KeyCategory::HIDDEN},
		{0xf6, "Reserved", KeyCategory::HIDDEN},
		{0xf7, "Reserved", KeyCategory::HIDDEN},
		{0xf8, "Reserved", KeyCategory::HIDDEN},
		{0xf9, "Reserved", KeyCategory::HIDDEN},
		{0xfa, "Reserved", KeyCategory::HIDDEN},
		{0xfb, "Reserved", KeyCategory::HIDDEN},
		{0xfc, "Reserved", KeyCategory::HIDDEN},
		{0xfd, "Reserved", KeyCategory::HIDDEN},
		{0xfe, "Reserved", KeyCategory::HIDDEN},
		{0xff, "Reserved", KeyCategory::HIDDEN}
	}
};

const std::vector<KeyboardLayout> KEYBOARD_LAYOUTS = {US, FRENCH, GERMAN};

const std::string KEY_CATEGORY_NAMES[NUM_KEY_CATEGORIES] =
{
	"Letter Keys",				// KeyCategory::LETTER
	"Number Keys",				// KeyCategory::NUMBER
	"Function Keys",			// KeyCategory::FUNCTION
	"Navigation and arrows",	// KeyCategory::NAV
	"Numpad Keys",				// KeyCategory::NUMPAD
	"Other Keys"				// KeyCategory::OTHER
};

const KeyCode* findKeyCode(const KeyboardLayout& layout, uint8_t code)
{
	for(unsigned int i = 0; i < sizeof(layout.keyCodes) / sizeof(KeyCode); i++)
		if(layout.keyCodes[i].code == code)
			return &layout.keyCodes[i];
	return NULL;
}
